## Groupby + agg

In [17]:
df.groupby('class').agg(list)

,sepal_width,sepal_height,petal_width,petal_height
class,,,,
Iris-setosa,"[5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, ...","[3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, ...","[1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, ...","[0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, ..."
Iris-versicolor,"[7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, ...","[3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, ...","[4.7, 4.5, 4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, ...","[1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1.0, 1.3, ..."
Iris-virginica,"[6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, ...","[3.3, 2.7, 3.0, 2.9, 3.0, 3.0, 2.5, 2.9, 2.5, ...","[6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, ...","[2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, ..."

In [18]:
df.groupby('class').agg(['max', 'min', 'sum', list])

                sepal_width              \
                        max  min    sum
class
Iris-setosa             5.8  4.3  250.3
Iris-versicolor         7.0  4.9  296.8
Iris-virginica          7.9  4.9  329.4

                                                                    \
                                                              list
class
Iris-setosa      [5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, ...
Iris-versicolor  [7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, ...
Iris-virginica   [6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, ...

                sepal_height              \
                         max  min    sum
class
Iris-setosa              4.4  2.3  170.9
Iris-versicolor          3.4  2.0  138.5
Iris-virginica           3.8  2.2  148.7

                                                                    \
                                                              list
class
Iris-setosa      [3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, ...
Iris-versicolor  [3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, ...
Iris-virginica   [3.3, 2.7, 3.0, 2.9, 3.0, 3.0, 2.5, 2.9, 2.5, ...

                petal_width              \
                        max  min    sum
class
Iris-setosa             1.9  1.0   73.2
Iris-versicolor         5.1  3.0  213.0
Iris-virginica          6.9  4.5  277.6

                                                                    \
                                                              list
class
Iris-setosa      [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, ...
Iris-versicolor  [4.7, 4.5, 4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, ...
Iris-virginica   [6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, ...

                petal_height              \
                         max  min    sum
class
Iris-setosa              0.6  0.1   12.2
Iris-versicolor          1.8  1.0   66.3
Iris-virginica           2.5  1.4  101.3


                                                              list
class
Iris-setosa      [0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, ...
Iris-versicolor  [1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1.0, 1.3, ...
Iris-virginica   [2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, ...